// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package protocol.p2
import com.google.protobuf.CodedInputStream

/** 测试协议
  */
@SerialVersionUID(0L)
final case class cs4(
    account: _root_.scala.Long,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[cs4] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = account
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, __value)
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      
      {
        val __v = account
        _output__.writeInt64(1, __v)
      };
      unknownFields.writeTo(_output__)
    }
    def withAccount(__v: _root_.scala.Long): cs4 = copy(account = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => account
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PLong(account)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: protocol.p2.cs4.type = protocol.p2.cs4
    // @@protoc_insertion_point(GeneratedMessage[protocol.cs4])
}

object cs4 extends scalapb.GeneratedMessageCompanion[protocol.p2.cs4] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[protocol.p2.cs4] = this
  override def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): protocol.p2.cs4 = {
    var __requiredFields0: _root_.scala.Long = 0x1L
    var __account: _root_.scala.Long = 0L
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __account = _input__.readInt64()
          __requiredFields0 &= 0xfffffffffffffffeL
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    if (__requiredFields0 != 0L) { throw new _root_.com.google.protobuf.InvalidProtocolBufferException("Message missing required fields.") } 
    protocol.p2.cs4(
        account = __account,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[protocol.p2.cs4] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      protocol.p2.cs4(
        account = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).get.as[_root_.scala.Long]
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = P2Proto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = P2Proto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = protocol.p2.cs4(
    account = 0L
  )
  implicit class cs4Lens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, protocol.p2.cs4]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, protocol.p2.cs4](_l) {
    def account: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.account)((c_, f_) => c_.copy(account = f_))
  }
  final val ACCOUNT_FIELD_NUMBER = 1
  def of(
    account: _root_.scala.Long
  ): _root_.protocol.p2.cs4 = _root_.protocol.p2.cs4(
    account
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[protocol.cs4])

  override def merge(a: cs4, input: CodedInputStream): cs4 = ???
}
